# Uses himself for configuration, simplifying things
spring:
   cloud:
      config:
         server:
            git:
               uri: file://${HOME}/git/SpringCloud/
               searchPaths: config

server:
  port: 8888