# Uses himself for configuration, simplifying things
spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/megamiun/SpringCloud
               searchPaths: 'config'