# Uses himself for configuration, simplifying things
spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/git/SpringCloud
          searchPaths: /config

server:
  port: 8888
