# Uses himself for configuration, simplifying things
spring:
  cloud:
    config:
      label: alt-uncorrected
      server:
        git:
          uri: https://github.com/megamiun/SpringCloud
          searchPaths: /config

server:
  port: 8888
