spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  rabbitmq:
    host: 10.200.5.211
    port: 5672
    username: ale
    password: ale

  jpa:
    - show-sql: true
    - properties:
      hibernate:
        format_sql: true

    - hibernate:
      ddl-auto: create

jsa:
  rabbitmq:
    queue: jsa.queue

application.name: receiver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka