spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""

  rabbitmq:
    host: 10.200.5.211
    port: 5672
    username: ale
    password: ale

  jpa:
    - show-sql: true
    - properties:
      hibernate:
        format_sql: true

    - hibernate:
      ddl-auto: create

jsa:
  rabbitmq:
    exchange: jsa.direct
    routingkey: jsa.routingkey

server:
  port: 8001

application.name: sender

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
